# disable ctrl-s suspend
stty stop undef

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

export EDITOR="vim"

zstyle :compinstall filename '/home/cocu/.zshrc'
autoload -Uz compinit
compinit
set wildmenu
set wrap
set showmatch
autoload colors
colors

setopt auto_cd
setopt auto_pushd
setopt auto_list
setopt correct
setopt list_packed
setopt nolistbeep

setopt ignore_eof
setopt rmstar_wait

#zsh UI
#case "${TERM}" in
#rxvt-256color)
#	ibus-daemon -drx
#	;;
#esac

#zsh PROMPT
case ${UID} in
0)
  PROMPT="%{${fg[red]}%}%n%# %{${reset_color}%}"
  #PROMPT2=
  #SPROMPT=
  RPROMPT="%{${fg[cyan]}%}[%~]%{${reset_color}%}"
  ;;
*)
  PROMPT="%{${fg[green]}%} _(:3｣_)_ %# %{${reset_color}%}"
  #PROMPT2=
  #SPROMPT=
  RPROMPT="%{${fg[cyan]}%}[%~]%{${reset_color}%}"
  ;;
esac

#python virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh
export PIP_RESPECT_VIRTUALENV=true

#alias
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -al'
alias tree='tree -N'
alias du='du -h'
alias df='df -h'
alias cd..='cd ..'
alias pingg='ping -c 3 www.google.co.jp'
alias less='less -R'

alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown'

alias grub-reboot='sudo grub-reboot'
alias sozsh='source ~/.zshrc'
alias :q='exit'
alias :Q='exit'
alias vi='vim'

alias ta='tmux_ornot'
alias xbg='feh --bg-scale'
alias pdb='python /usr/lib/python2.7/pdb.py'
alias up='cd ..'
alias multimc='XMODIFIERS= /home/cocu/etc/multimc/MultiMC'
alias ocaml='ledit ocaml'

alias mitmproxy-p9999='mitmproxy -p 9999'
alias simplehttpserver='python -m http.server'
alias cgihttpserver='python -m http.server --cgi'

alias highlight='pygmentize -O style=monokai -f console256 -g'
alias virtualenvwrapper='source /usr/bin/virtualenvwrapper.sh'

#mba
alias dropboxrestart='dropbox stop;dropbox start'
alias うぃふぃ='wicd-curses'
alias tmux='tmux -2'


# path
export PATH=$PATH:/home/cocu/bin/bin-git/twitter
export PATH=$PATH:/home/cocu/bin/bin-git/utils
export PATH=$PATH:/home/cocu/bin/utils
export PATH=$PATH:/home/cocu/bin/coins-tools
export PATH=$PATH:/home/cocu/bin/coins-utils

# .zshrc.d

if [ -d .zshrc.d ]; then
  for file in `find ~/.zshrc.d -mindepth 1`; do
    source $file
  done
fi

export PYTHONSTARTUP=~/.config/python/startup.py
